layout_spectrum: 0.9710821
typography_spectrum: 0.6781716
color:
  saturation: 0.7392724
  lightness: 0.4752798
  brandStrength: 0.201959
  rhythmicContrast: 0.6385261
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Employerofmagic
